services:
  backend:
    build:
      context: ./backend
    image: puppet-backend:local
    container_name: puppet-backend
    restart: always
    ports:
      - "4000:4000"
    env_file:
      - backend/.env
    networks:
      - puppet-network

  frontend:
    build:
      context: ./frontend
    image: puppet-frontend:local
    container_name: puppet-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - puppet-network

networks:
  puppet-network:
    driver: bridge
